### ISSUE TITLE
Unique words or all words

### ISSUE THREAD

**Issue by nikcorg** [wunderdogsw/wunderpahkina-vol8#3]
Should all words in the story be preserved or only unique words? The example doesn't suffer from word repetition, so it's impossible to tell.

Also, if it is significant, is a word's uniqueness defined in a case-sensitive or case-insensitive manner?

**Comment by epavese** [comment]
You can easily check that 1) it requires to have the exact same words, not unique words and 2) it is case-sensitive

**Comment by heikkipora** [comment]
Looks like all the words should be preserved. The result does not pass the official validator if only unique words are preserved.

**Comment by nikcorg** [comment]
Thx.
